version: '3.1'

services:
  database:
    container_name: app_database
    image: mongo:8.0.6
    volumes:
      - ./mongo_db:/data/db
    networks:
      - database
    env_file:
      - mongo.env

networks:
  database:
